In [20]:
import numpy as np
a=np.array([1,2,3])
c=np.arange(0,10,2)            # range 
d=np.arange(1,11,2)
b=np.linspace(0,1,5)
print(a)
print(b)
print(c)
print(d)
print(np.linspace(1,5,11)) #divide the number by 6  default 50
print(np.linspace(0,10,5,endpoint=False))

[1 2 3]
[0.   0.25 0.5  0.75 1.  ]
[0 2 4 6 8]
[1 3 5 7 9]
[1.  1.4 1.8 2.2 2.6 3.  3.4 3.8 4.2 4.6 5. ]
[0. 2. 4. 6. 8.]


1D,2D,3D array

In [22]:
arr_1d=np.array([1,2,3])           #1D
arr_2d=np.array([[1,2,3],[4,5,6]])
arr_3d=np.array([[[1,2],[3,4],[5,6]]])
print(arr_1d,"\n")
print(arr_2d,"\n")
print(arr_3d)

[1 2 3] 

[[1 2 3]
 [4 5 6]] 

[[[1 2]
  [3 4]
  [5 6]]]


special array

In [26]:
z=np.zeros((2,3))
o=np.ones((2,3))
i=np.identity(3)
f=np.full((3,4),7)
print(f"zeros: {z}\n")
print(f"ones: {o}\n")
print(f"identity: {i}\n")
print(f"full: {f}\n")

zeros: [[0. 0. 0.]
 [0. 0. 0.]]

ones: [[1. 1. 1.]
 [1. 1. 1.]]

identity: [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

full: [[7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]]



array attributes

In [38]:
arr=np.array([[1,2,3],[4,5,6]])
print(f"shape:{arr.shape}")
print(f"size:{arr.size}")
print(f"dimention:{arr.ndim}")
print(f"datatype:{arr.dtype}")

shape:(2, 3)
size:6
dimention:2
datatype:int32


accessing array elements

In [46]:
ar=np.array([1,2,3,4,5])
print(ar[0])
print(ar[-1])
print(ar[::2])
ar1=np.array([[1,2,3],[4,5,6],[7,9,10]])
print(ar1[0:3,1:3])
print(ar1[:,0:2])


1
5
[1 3 5]
[[ 2  3]
 [ 5  6]
 [ 9 10]]
[[1 2]
 [4 5]
 [7 9]]


array operations

In [48]:
#arithmetic operation
a1=np.array([1,2,3])
b1=np.array([4,5,6])
print(a1+b1)
print(a1-b1)
print(a1*b1)
print(a1/b1)


[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]


In [61]:
#broadcasting
arr2=np.array([[1,2,4],[5,6,3]])
b2=np.array([10,20,30])
print(arr2+b2)

c=np.array([[1],[2],[3]])
print(c)
d=np.array([10,20,30])
print(c+d)

[[11 22 34]
 [15 26 33]]
[[1]
 [2]
 [3]]
[[11 21 31]
 [12 22 32]
 [13 23 33]]


In [60]:
#scalar
arrr=np.array([1,2,3])
print(arrr**2)
print(arrr+10)
print(arrr*2)
print(arrr/2)


[1 4 9]
[11 12 13]
[2 4 6]
[0.5 1.  1.5]
