# Creating arrays

In [1]:
#1)
import numpy as np
a=np.array([15,22,8,19,31])
print(a)


[15 22  8 19 31]


In [5]:
#2)
b=np.arange(2,21,2)
print(b)
print(np.linspace(0,5,6))


[ 2  4  6  8 10 12 14 16 18 20]
[0. 1. 2. 3. 4. 5.]


# Types of arrays

In [8]:
#3)
arr_1d=np.array([1,2,3,4])
arr_2d=np.array([[1,2,3],[4,5,6]])
arr_3d=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(arr_1d)
print(f"Dimension:{arr_1d.ndim}")
print(arr_2d)
print(f"dimension:{arr_2d.ndim}")
print(arr_3d)
print(f"dimension:{arr_3d.ndim}")

[1 2 3 4]
Dimension:1
[[1 2 3]
 [4 5 6]]
dimension:2
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
dimension:3


# Special arrays

In [10]:
#4)
z=np.zeros((3,3))
o=np.ones((2,4))
i=np.identity(4)
f=np.full((3,3),6)
print(f"Zeros : {z}\n")
print(f"Ones: {o}\n")
print(f"Identity: {i}\n")
print(f" Full: {f}\n")

Zeros : [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

Ones: [[1. 1. 1. 1.]
 [1. 1. 1. 1.]]

Identity: [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]

 Full: [[6 6 6]
 [6 6 6]
 [6 6 6]]



In [20]:
#5)
arr=np.ones((5,5))
arr[0, :]=0
arr[-1,:]=0
arr[:,0]=0
arr[:,-1]=0
print(arr)

[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


# Array attributes

In [22]:
#6)
ar=np.array([[4,5,6,7],[8,9,10,11],[12,13,14,15]])
print(f"shape: {ar.shape}")
print(f"size: {ar.size}")
print(f"datatype: {ar.dtype}")
print(f"dimension: {ar.ndim}")

shape: (3, 4)
size: 12
datatype: int64
dimension: 2


# Basic indexing

In [23]:
#7)
arr=np.array([21,34,42,18,55,9,60])
print(arr[0])
print(arr[-1])
print(arr[3])

21
60
18


In [24]:
#8)
mat=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(mat[1,2])
print(mat[-2,-1])

6
6


# Slicing techniques

In [32]:
#9)
ar=np.array([5,10,15,20,25,30,35,40])
print(ar[:4])
print(ar[::2])
print(ar[::-1])

[ 5 10 15 20]
[ 5 15 25 35]
[40 35 30 25 20 15 10  5]


In [35]:
#10)
mat=np.array([[10,20,30],[40,50,60],[70,80,90]])
print(mat[0:2,1:])
print(mat[0:,1])

[[20 30]
 [50 60]]
[20 50 80]


In [39]:
#11)
arr=np.array([1,2,3,4,5,6,7,8,9,10])
print(arr[-3:])

[ 8  9 10]


# Aritmetic operations

In [40]:
#12)
a=np.array([10,20,30,40])
b=np.array([1,2,3,4])
print(a+b)
print(a-b)
print(a*b)
print(a/b)

[11 22 33 44]
[ 9 18 27 36]
[ 10  40  90 160]
[10. 10. 10. 10.]


In [41]:
#13)
price=np.array([250,180,420,90])
quantity=np.array([3,5,2,10])
total_cost=price*quantity
print(total_cost)
overall_total=total_cost.sum()
print(overall_total)


[750 900 840 900]
3390


# Broadcasting and Scalar

In [45]:
#14)
marks=np.array([[45,60,55],[70,65,80],[50,55,60]])
print(marks+5, "\n")
bonus=np.array([5,10,2])
print(marks+bonus)

[[50 65 60]
 [75 70 85]
 [55 60 65]] 

[[50 70 57]
 [75 75 82]
 [55 65 62]]


In [48]:
#15)
arr=np.array([1,2,3,4,5])
arr=arr*10
print(arr)
a=np.array([1,1,1,1,1])
print(arr+a)

[10 20 30 40 50]
[11 21 31 41 51]
